apiVersion: v1
kind: ServiceAccount
metadata:
  name: pdcm-labelstudio-service-account
  namespace: pdcm-labelstudio
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pdcm-labelstudio-deployment-access
  namespace: pdcm-labelstudio
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
- apiGroups:
  - "apps"
  resources:
  - deployments
  - replicasets
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
- apiGroups:
  - "extensions"
  resources:
  - deployments
  - replicasets
  - ingresses
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pdcm-labelstudio-deployment-access-binding
  namespace: pdcm-labelstudio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pdcm-labelstudio-deployment-access
subjects:
- kind: ServiceAccount
  name: pdcm-labelstudio-deployment
  namespace: pdcm-labelstudio