apiVersion: v1
kind: Service
metadata:
  labels:
    app: pdcm-labelstudio
  name: pdcm-labelstudio-svc
  namespace: pdcm-labelstudio
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32523
  selector:
    app: pdcm-labelstudio
  type: NodePort
status:
  loadBalancer: {}