apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdcm-labelstudio-pvc
  labels:
    app: lectern
  namespace: pdcm-labelstudio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard-nfs-production